### ISSUE TITLE
Unable to start service

### ISSUE THREAD

**Issue by daimoniuma** [Ashish-Bansal/OneTapVideoDownload#14] opened 2016-12-02 23:30 UTC
`W/ActivityManager(1331): Unable to start service Intent { cmp=com.simplecity.amp_pro/com.phantom.onetapvideodownload.IpcService } U=0: not found`

Strange issue...

**Comment by Ashish-Bansal** [comment] 2016-12-03 09:18
Well the output is indeed strange. Intent specified is wrong. It should be 

`cmp=com.phantom.onetapvideodownload/com.phantom.onetapvideodownload.IpcService }`

Is this reoccurring ? Try clearing logs or rebooting your device.

I can't test it on my device as `com.simplecity.amp_pro` application is paid. Anyway, I don't think that application does any streaming over network, or does it ? If no, then intent sent to the OTVD would be just ignored. 

But if this is happening for some other application which streams content over network, then I surely will inspect this issue.

**Comment by daimoniuma** [comment] 2016-12-03 09:43
Yes, this issue always appears when I try to play mp3 from external SD. You can test it with free version.

https://play.google.com/store/apps/details?id=another.music.player

**Comment by Ashish-Bansal** [comment] 2016-12-03 10:37
Okay, I'll check it out.

**Comment by Ashish-Bansal** [comment] 2017-01-02 11:33
Stackoverflow Question : http://stackoverflow.com/questions/41425703/activitymanager-unable-to-start-service-intent

**Comment by Ashish-Bansal** [comment] 2018-04-08 11:44
I'm unable to reproduce this issue now. Not sure what in #108 fixed it.
Closing it.

**Closed as completed by Ashish-Bansal** 2018-04-08 11:44 UTC
Labels: bug, help wanted
