### ISSUE TITLE
Inspect media URL

### ISSUE THREAD

**Issue by daimoniuma** [Ashish-Bansal/OneTapVideoDownload#15] opened 2016-12-03 09:51 UTC
Could you correctly process unsupported URLs?

`E/IpcService(21302): com.phantom.onetapvideodownload.action.inspectmediaurl`

**Comment by Ashish-Bansal** [comment] 2016-12-03 10:34
Inspect Media URL is for videos which are being played in the applications using WebView. Try playing vimeo/youtube videos in Cyanogen Mod's default Browser. It should show download notification.

**Comment by daimoniuma** [comment] 2016-12-03 10:54
What?

1. I don't use Cyanogen Mod.
2. I didn't talk that I don't receive notifications. I have notifications for videos, all is ok.
3. Your media inspector collects all links which go through WebView. Not only videos. Because I didn't see any videos in this session.
4. Seems like some (not videos) links cannot be correctly processed.
5. This may leads to unexpected memory leak.

Why did you close the issue?

**Comment by Ashish-Bansal** [comment] 2016-12-03 11:12
> I don't use Cyanogen Mod.

In that case, try using any browser which uses this[0].

> I didn't talk that I don't receive notifications. I have notifications for videos, all is ok.
> Your media inspector collects all links which go through WebView. Not only videos. Because I didn't see any videos in this session.
> Seems like some (not videos) links cannot be correctly processed.

Yes, media inspector collects all the requests sent by the webview and checks the reponse headers. If it's a video(checked through response headers), then it shows the notification.

> This may leads to unexpected memory leak.

Could you please explain how can this lead to memory leak ? 

> Why did you close the issue? 

Because it's expected behaviour. I couldn't find anything wrong with this. If you still think something is wrong, I have reopened the issue. Please explain.

[0] https://developer.android.com/reference/android/webkit/WebView.html

**Comment by daimoniuma** [comment] 2016-12-03 11:31
> In that case, try using any browser which uses this.

Why should I use something else? I'm not trying to get videos from this browser.

> Yes, media inspector collects all the requests sent by the webview and checks the reponse headers. If it's a video (checked through response headers), then it shows the notification.

Seems like this check isn't working for some requests (https or php, IDK).

> Could you please explain how can this lead to memory leak?

When some process under Xposed call the error into logs, it raises concerns.

> Because it's expected behaviour.

Expected? 😯 So could you depress this error?

**Comment by Ashish-Bansal** [comment] 2016-12-03 11:36
> When some process under Xposed call the error into logs, it raises concerns.
> Expected? 😯 So could you depress this error?

Actually it's not an 'Error'. It's under wrong tag "E". It's quite old code, so printed under wrong tag (It should be under 'V'). So, I guess you thought it's an error.

**Comment by daimoniuma** [comment] 2016-12-03 11:54
So it's a fault of Catlog, right?

**Comment by daimoniuma** [comment] 2016-12-03 11:55
Anyway I think you could depress this messages.

**Comment by Ashish-Bansal** [comment] 2016-12-03 11:57
Yeah, I'll depress this message to "Info" category in the next release.

**Comment by daimoniuma** [comment] 2016-12-03 11:57
Thanks!

**Comment by Ashish-Bansal** [comment] 2016-12-03 21:32
Fixed with 35cb4d72bd82a5e510edae98213c423a3a608122.

**Closed as completed by Ashish-Bansal** 2016-12-03 21:33 UTC
Labels: Need Info
